### ISSUE TITLE
running "multicam_trackwise_evaluation.py" gives me bellow error. Kindly help me the fix it

### ISSUE THREAD

**Issue by ssbilakeri** [nolanzzz/mtmct#4]
Traceback (most recent call last):
  File "multicam_trackwise_evaluation.py", line 383, in <module>
    result = Multicam_trackwise_evaluation(dataset_folder="/home/mca/Downloads/wda_tracker-master/MTA_ext_short/test"
  File "multicam_trackwise_evaluation.py", line 195, in evaluate
    track_eval_res_df = self.get_track_eval_res_df(summary)
  File "multicam_trackwise_evaluation.py", line 275, in get_track_eval_res_df
    idx_hids = id_global_assignment["idx_hids"]
KeyError: 'idx_hids'

**Comment by nolanzzz** [comment]
This is an error from the original wda_tracker repository. I tried to fix it but failed. I suspect this is caused by a version difference on the motmetrics library, I used [motmetrics_evaluation.py](https://github.com/nolanzzz/mtmct/blob/main/evaluation/motmetrics_evaluation.py) for the most part. Will try to fix this when time allows.

**Comment by ssbilakeri** [comment]
Dear  Nolan Zhang,
Thank you for your quick response.  How did you visualize multi camera
tracking results. if you have some code that please share, it will help me
a lot.
